name : Actions Workflow

on : 
  pull_request:
    types:
      - closed
      - assigned
      - reopened
      - closed
  schedule: 
    - cron: "0/5 * * * *"
  


jobs :
  run-github-actions:
   runs-on : ubuntu-latest
   steps: 
     - name: simple JS Actions
       uses: actions/hello-world-javascript-action@v1
       with : 
         who-to-greet : Moe

     - name : Log Greeting time
       run : echo "{{steps.greet.outputs.time}}"
     - name : List files 
       run  : |
         pwd
         ls
     - name : Checkout 
       uses : actions/checkout@v1
     - name : List files 
       run  : |
         pwd
         ls
         echo $GITHUB_SHA
         echo $GITHUB_REPOSITORY
         echo $GITHUB_WORKSPACE
         echo $GITHUB_TOKEN
         
     

     


